### ISSUE TITLE
git LFS für die Bilder

### ISSUE THREAD

**Issue by 24367dfa** [netz39/n39-jekyll-webpage#12]
https://docs.github.com/en/repositories/working-with-files/managing-large-files/moving-a-file-in-your-repository-to-git-large-file-storage

**Comment by 24367dfa** [comment]
Installation instructions: https://github.com/git-lfs/git-lfs#getting-started

**Comment by 24367dfa** [comment]
Filetypes: .PNG, .jpg, .JPEG, .pfd

**Comment by LeSpocky** [comment]
Ein Hinweis im README.md dass Git LFS benutzt wird und was man in seinem Client dazu anstellen muss, wäre ~~git~~ gut.
