### ISSUE TITLE
Kontaktpage Discord-Link broken

### ISSUE THREAD

**Issue by timherrm** [netz39/n39-jekyll-webpage#21]
https://www.netz39.de/kontakt/ da geht der Discord Link nicht. Fehlt da nur das https:// oder woran liegt das?

**Comment by MG-5** [comment]
Japp, das https:// fehlt

**Comment by MG-5** [comment]
Wollen wir den Reiter von "Kommunikation" gleich zu "Kontakt" ändern?

**Comment by 24367dfa** [comment]
> Wollen wir den Reiter von "Kommunikation" gleich zu "Kontakt" ändern?

ja, mach ich
